//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLAB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CheckIn { get; set; }
        public Nullable<System.DateTime> CheckOut { get; set; }
        public string IDEmployee { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
